name: per-capita-football-scraping
on: [push]
jobs:
    Explore-Github-Actions:
        runs-on: ubuntu-latest
        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write
        steps: 
           - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
           - name: Check out repository code
             uses: actions/checkout@v3
           - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
           - name: Scrape and output JSON
             run: |
              npm install
              node ${{ github.workspace }}/main.js > ${{ github.workspace }}/output.json
           - uses: stefanzweifel/git-auto-commit-action@v4
           - run: echo "This job's status is ${{ job.status }}."