name: per-capita-football-scraping
on: [push]
jobs:
    Explore-Github-Actions:
        runs-on: ubuntu-latest
        steps: 
           - run: echo "The job was automatically triggered by a ${{ github. event_name }} event."
           - name: Check out repository code
             uses: actions/checkout@v2
           - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
           - name: List files in the repository 
             run: |
              npm install
              node ${{ github.workspace }}/main.js
           - run: echo "This job's status is ${{ job.status }}."