name: per-capita-football-scraping
on: [push]
jobs:
    Explore-Github-Actions:
        runs-on: ubuntu-latest
        steps: 
           - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
           - name: Check out repository code
             uses: actions/checkout@v3
           - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
           - name: Scrape and output JSON
             run: |
              npm install
              node ${{ github.workspace }}/main.js > ${{ github.workspace }}/output.json
           - run: echo "This job's status is ${{ job.status }}."
           - run: |
                git config --global user.email "manuelrydholm@gmail.com"
                git config --global user.name "finalManu"
                git add .
                git commit -m "Update JSON `date`"
                git push